# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Develop\CMake\bin\cmake.exe

# The command to remove a file.
RM = C:\Develop\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Dropbox\Work\biu\opensource\forced_alignment\forced_alignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Dropbox\Work\biu\opensource\forced_alignment\forced_alignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\Develop\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\Develop\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\Develop\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\Develop\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\Develop\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\Develop\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dropbox\Work\biu\opensource\forced_alignment\forced_alignment\CMakeFiles D:\Dropbox\Work\biu\opensource\forced_alignment\forced_alignment\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dropbox\Work\biu\opensource\forced_alignment\forced_alignment\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ForcedAlignmentDecode

# Build rule for target.
ForcedAlignmentDecode: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ForcedAlignmentDecode
.PHONY : ForcedAlignmentDecode

# fast build rule for target.
ForcedAlignmentDecode/fast:
	$(MAKE) -f CMakeFiles\ForcedAlignmentDecode.dir\build.make CMakeFiles/ForcedAlignmentDecode.dir/build
.PHONY : ForcedAlignmentDecode/fast

#=============================================================================
# Target rules for targets named ForcedAlignmentTrain

# Build rule for target.
ForcedAlignmentTrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ForcedAlignmentTrain
.PHONY : ForcedAlignmentTrain

# fast build rule for target.
ForcedAlignmentTrain/fast:
	$(MAKE) -f CMakeFiles\ForcedAlignmentTrain.dir\build.make CMakeFiles/ForcedAlignmentTrain.dir/build
.PHONY : ForcedAlignmentTrain/fast

#=============================================================================
# Target rules for targets named cmd_line

# Build rule for target.
cmd_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 cmd_line
.PHONY : cmd_line

# fast build rule for target.
cmd_line/fast:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/build
.PHONY : cmd_line/fast

#=============================================================================
# Target rules for targets named forced_alignment

# Build rule for target.
forced_alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 forced_alignment
.PHONY : forced_alignment

# fast build rule for target.
forced_alignment/fast:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/build
.PHONY : forced_alignment/fast

#=============================================================================
# Target rules for targets named infra

# Build rule for target.
infra: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 infra
.PHONY : infra

# fast build rule for target.
infra/fast:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/build
.PHONY : infra/fast

libs/cmd_line/src/cmd_line.obj: libs/cmd_line/src/cmd_line.cpp.obj
.PHONY : libs/cmd_line/src/cmd_line.obj

# target to build an object file
libs/cmd_line/src/cmd_line.cpp.obj:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/libs/cmd_line/src/cmd_line.cpp.obj
.PHONY : libs/cmd_line/src/cmd_line.cpp.obj

libs/cmd_line/src/cmd_line.i: libs/cmd_line/src/cmd_line.cpp.i
.PHONY : libs/cmd_line/src/cmd_line.i

# target to preprocess a source file
libs/cmd_line/src/cmd_line.cpp.i:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/libs/cmd_line/src/cmd_line.cpp.i
.PHONY : libs/cmd_line/src/cmd_line.cpp.i

libs/cmd_line/src/cmd_line.s: libs/cmd_line/src/cmd_line.cpp.s
.PHONY : libs/cmd_line/src/cmd_line.s

# target to generate assembly for a file
libs/cmd_line/src/cmd_line.cpp.s:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/libs/cmd_line/src/cmd_line.cpp.s
.PHONY : libs/cmd_line/src/cmd_line.cpp.s

libs/infra/src/infra_binary.obj: libs/infra/src/infra_binary.cpp.obj
.PHONY : libs/infra/src/infra_binary.obj

# target to build an object file
libs/infra/src/infra_binary.cpp.obj:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_binary.cpp.obj
.PHONY : libs/infra/src/infra_binary.cpp.obj

libs/infra/src/infra_binary.i: libs/infra/src/infra_binary.cpp.i
.PHONY : libs/infra/src/infra_binary.i

# target to preprocess a source file
libs/infra/src/infra_binary.cpp.i:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_binary.cpp.i
.PHONY : libs/infra/src/infra_binary.cpp.i

libs/infra/src/infra_binary.s: libs/infra/src/infra_binary.cpp.s
.PHONY : libs/infra/src/infra_binary.s

# target to generate assembly for a file
libs/infra/src/infra_binary.cpp.s:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_binary.cpp.s
.PHONY : libs/infra/src/infra_binary.cpp.s

libs/infra/src/infra_exception.obj: libs/infra/src/infra_exception.cpp.obj
.PHONY : libs/infra/src/infra_exception.obj

# target to build an object file
libs/infra/src/infra_exception.cpp.obj:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_exception.cpp.obj
.PHONY : libs/infra/src/infra_exception.cpp.obj

libs/infra/src/infra_exception.i: libs/infra/src/infra_exception.cpp.i
.PHONY : libs/infra/src/infra_exception.i

# target to preprocess a source file
libs/infra/src/infra_exception.cpp.i:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_exception.cpp.i
.PHONY : libs/infra/src/infra_exception.cpp.i

libs/infra/src/infra_exception.s: libs/infra/src/infra_exception.cpp.s
.PHONY : libs/infra/src/infra_exception.s

# target to generate assembly for a file
libs/infra/src/infra_exception.cpp.s:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_exception.cpp.s
.PHONY : libs/infra/src/infra_exception.cpp.s

libs/infra/src/infra_mm_funcs.obj: libs/infra/src/infra_mm_funcs.cpp.obj
.PHONY : libs/infra/src/infra_mm_funcs.obj

# target to build an object file
libs/infra/src/infra_mm_funcs.cpp.obj:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_mm_funcs.cpp.obj
.PHONY : libs/infra/src/infra_mm_funcs.cpp.obj

libs/infra/src/infra_mm_funcs.i: libs/infra/src/infra_mm_funcs.cpp.i
.PHONY : libs/infra/src/infra_mm_funcs.i

# target to preprocess a source file
libs/infra/src/infra_mm_funcs.cpp.i:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_mm_funcs.cpp.i
.PHONY : libs/infra/src/infra_mm_funcs.cpp.i

libs/infra/src/infra_mm_funcs.s: libs/infra/src/infra_mm_funcs.cpp.s
.PHONY : libs/infra/src/infra_mm_funcs.s

# target to generate assembly for a file
libs/infra/src/infra_mm_funcs.cpp.s:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_mm_funcs.cpp.s
.PHONY : libs/infra/src/infra_mm_funcs.cpp.s

libs/infra/src/infra_vm_funcs.obj: libs/infra/src/infra_vm_funcs.cpp.obj
.PHONY : libs/infra/src/infra_vm_funcs.obj

# target to build an object file
libs/infra/src/infra_vm_funcs.cpp.obj:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vm_funcs.cpp.obj
.PHONY : libs/infra/src/infra_vm_funcs.cpp.obj

libs/infra/src/infra_vm_funcs.i: libs/infra/src/infra_vm_funcs.cpp.i
.PHONY : libs/infra/src/infra_vm_funcs.i

# target to preprocess a source file
libs/infra/src/infra_vm_funcs.cpp.i:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vm_funcs.cpp.i
.PHONY : libs/infra/src/infra_vm_funcs.cpp.i

libs/infra/src/infra_vm_funcs.s: libs/infra/src/infra_vm_funcs.cpp.s
.PHONY : libs/infra/src/infra_vm_funcs.s

# target to generate assembly for a file
libs/infra/src/infra_vm_funcs.cpp.s:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vm_funcs.cpp.s
.PHONY : libs/infra/src/infra_vm_funcs.cpp.s

libs/infra/src/infra_vv_funcs.obj: libs/infra/src/infra_vv_funcs.cpp.obj
.PHONY : libs/infra/src/infra_vv_funcs.obj

# target to build an object file
libs/infra/src/infra_vv_funcs.cpp.obj:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vv_funcs.cpp.obj
.PHONY : libs/infra/src/infra_vv_funcs.cpp.obj

libs/infra/src/infra_vv_funcs.i: libs/infra/src/infra_vv_funcs.cpp.i
.PHONY : libs/infra/src/infra_vv_funcs.i

# target to preprocess a source file
libs/infra/src/infra_vv_funcs.cpp.i:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vv_funcs.cpp.i
.PHONY : libs/infra/src/infra_vv_funcs.cpp.i

libs/infra/src/infra_vv_funcs.s: libs/infra/src/infra_vv_funcs.cpp.s
.PHONY : libs/infra/src/infra_vv_funcs.s

# target to generate assembly for a file
libs/infra/src/infra_vv_funcs.cpp.s:
	$(MAKE) -f CMakeFiles\infra.dir\build.make CMakeFiles/infra.dir/libs/infra/src/infra_vv_funcs.cpp.s
.PHONY : libs/infra/src/infra_vv_funcs.cpp.s

src/Classifier.obj: src/Classifier.cpp.obj
.PHONY : src/Classifier.obj

# target to build an object file
src/Classifier.cpp.obj:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Classifier.cpp.obj
.PHONY : src/Classifier.cpp.obj

src/Classifier.i: src/Classifier.cpp.i
.PHONY : src/Classifier.i

# target to preprocess a source file
src/Classifier.cpp.i:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Classifier.cpp.i
.PHONY : src/Classifier.cpp.i

src/Classifier.s: src/Classifier.cpp.s
.PHONY : src/Classifier.s

# target to generate assembly for a file
src/Classifier.cpp.s:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Classifier.cpp.s
.PHONY : src/Classifier.cpp.s

src/Dataset.obj: src/Dataset.cpp.obj
.PHONY : src/Dataset.obj

# target to build an object file
src/Dataset.cpp.obj:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Dataset.cpp.obj
.PHONY : src/Dataset.cpp.obj

src/Dataset.i: src/Dataset.cpp.i
.PHONY : src/Dataset.i

# target to preprocess a source file
src/Dataset.cpp.i:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Dataset.cpp.i
.PHONY : src/Dataset.cpp.i

src/Dataset.s: src/Dataset.cpp.s
.PHONY : src/Dataset.s

# target to generate assembly for a file
src/Dataset.cpp.s:
	$(MAKE) -f CMakeFiles\forced_alignment.dir\build.make CMakeFiles/forced_alignment.dir/src/Dataset.cpp.s
.PHONY : src/Dataset.cpp.s

src/ForcedAlignmentDecode.obj: src/ForcedAlignmentDecode.cpp.obj
.PHONY : src/ForcedAlignmentDecode.obj

# target to build an object file
src/ForcedAlignmentDecode.cpp.obj:
	$(MAKE) -f CMakeFiles\ForcedAlignmentDecode.dir\build.make CMakeFiles/ForcedAlignmentDecode.dir/src/ForcedAlignmentDecode.cpp.obj
.PHONY : src/ForcedAlignmentDecode.cpp.obj

src/ForcedAlignmentDecode.i: src/ForcedAlignmentDecode.cpp.i
.PHONY : src/ForcedAlignmentDecode.i

# target to preprocess a source file
src/ForcedAlignmentDecode.cpp.i:
	$(MAKE) -f CMakeFiles\ForcedAlignmentDecode.dir\build.make CMakeFiles/ForcedAlignmentDecode.dir/src/ForcedAlignmentDecode.cpp.i
.PHONY : src/ForcedAlignmentDecode.cpp.i

src/ForcedAlignmentDecode.s: src/ForcedAlignmentDecode.cpp.s
.PHONY : src/ForcedAlignmentDecode.s

# target to generate assembly for a file
src/ForcedAlignmentDecode.cpp.s:
	$(MAKE) -f CMakeFiles\ForcedAlignmentDecode.dir\build.make CMakeFiles/ForcedAlignmentDecode.dir/src/ForcedAlignmentDecode.cpp.s
.PHONY : src/ForcedAlignmentDecode.cpp.s

src/ForcedAlignmentTrain.obj: src/ForcedAlignmentTrain.cpp.obj
.PHONY : src/ForcedAlignmentTrain.obj

# target to build an object file
src/ForcedAlignmentTrain.cpp.obj:
	$(MAKE) -f CMakeFiles\ForcedAlignmentTrain.dir\build.make CMakeFiles/ForcedAlignmentTrain.dir/src/ForcedAlignmentTrain.cpp.obj
.PHONY : src/ForcedAlignmentTrain.cpp.obj

src/ForcedAlignmentTrain.i: src/ForcedAlignmentTrain.cpp.i
.PHONY : src/ForcedAlignmentTrain.i

# target to preprocess a source file
src/ForcedAlignmentTrain.cpp.i:
	$(MAKE) -f CMakeFiles\ForcedAlignmentTrain.dir\build.make CMakeFiles/ForcedAlignmentTrain.dir/src/ForcedAlignmentTrain.cpp.i
.PHONY : src/ForcedAlignmentTrain.cpp.i

src/ForcedAlignmentTrain.s: src/ForcedAlignmentTrain.cpp.s
.PHONY : src/ForcedAlignmentTrain.s

# target to generate assembly for a file
src/ForcedAlignmentTrain.cpp.s:
	$(MAKE) -f CMakeFiles\ForcedAlignmentTrain.dir\build.make CMakeFiles/ForcedAlignmentTrain.dir/src/ForcedAlignmentTrain.cpp.s
.PHONY : src/ForcedAlignmentTrain.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... install/local
	@echo ... install/strip
	@echo ... edit_cache
	@echo ... install
	@echo ... rebuild_cache
	@echo ... ForcedAlignmentTrain
	@echo ... ForcedAlignmentDecode
	@echo ... list_install_components
	@echo ... forced_alignment
	@echo ... cmd_line
	@echo ... infra
	@echo ... libs/cmd_line/src/cmd_line.obj
	@echo ... libs/cmd_line/src/cmd_line.i
	@echo ... libs/cmd_line/src/cmd_line.s
	@echo ... libs/infra/src/infra_binary.obj
	@echo ... libs/infra/src/infra_binary.i
	@echo ... libs/infra/src/infra_binary.s
	@echo ... libs/infra/src/infra_exception.obj
	@echo ... libs/infra/src/infra_exception.i
	@echo ... libs/infra/src/infra_exception.s
	@echo ... libs/infra/src/infra_mm_funcs.obj
	@echo ... libs/infra/src/infra_mm_funcs.i
	@echo ... libs/infra/src/infra_mm_funcs.s
	@echo ... libs/infra/src/infra_vm_funcs.obj
	@echo ... libs/infra/src/infra_vm_funcs.i
	@echo ... libs/infra/src/infra_vm_funcs.s
	@echo ... libs/infra/src/infra_vv_funcs.obj
	@echo ... libs/infra/src/infra_vv_funcs.i
	@echo ... libs/infra/src/infra_vv_funcs.s
	@echo ... src/Classifier.obj
	@echo ... src/Classifier.i
	@echo ... src/Classifier.s
	@echo ... src/Dataset.obj
	@echo ... src/Dataset.i
	@echo ... src/Dataset.s
	@echo ... src/ForcedAlignmentDecode.obj
	@echo ... src/ForcedAlignmentDecode.i
	@echo ... src/ForcedAlignmentDecode.s
	@echo ... src/ForcedAlignmentTrain.obj
	@echo ... src/ForcedAlignmentTrain.i
	@echo ... src/ForcedAlignmentTrain.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

